name: stackrs
description: "Stackrs Mobile App"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  timeago: ^3.7.0
  http_parser: ^4.1.2
  flutter_gen: ^5.10.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0+1
  retrofit: ^4.4.2
  freezed_annotation: ^3.0.0
  dfunc: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/

  fonts:
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter-Light.ttf
            weight: 300
          - asset: assets/fonts/Inter-Regular.ttf
            weight: 400
          - asset: assets/fonts/Inter-Bold.ttf
            weight: 700
flutter_gen:
  output: lib/generated/
  line_length: 80
    
  integrations:
    flutter_svg: true
