name: lao_instruments
description: "lao_instruments Mobile App"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  timeago: ^3.7.0
  http_parser: ^4.1.2
  flutter_gen: ^5.10.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0+1
  retrofit: ^4.4.2
  freezed_annotation: ^2.4.4
  dfunc: ^0.10.0
  flutter_svg: ^2.0.17
  json_annotation: ^4.9.0
  flutter_slidable: ^4.0.0
  flutter_form_builder: ^10.0.0
  currency_text_input_formatter: ^2.2.9
  flutter_launcher_icons: ^0.14.3
  logger: ^2.5.0
  hive_generator: ^2.0.1
  uuid: ^4.5.1
  image_picker: ^1.1.2
  record: ^6.0.0
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  just_audio: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0 
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
flutter_gen:
  output: lib/generated/
  line_length: 80
    
  integrations:
    flutter_svg: true
